extends Node

onready var throwable_instance = preload("res://Entities/Objects/Throwable/Throwable.tscn")

enum types {
	General,
	Head_armor,
	Arm_armor,
	Torso_armor,
	Leg_armor,
	Shoes,
	Weapon,
	Amulet,
	Usable,
}

enum armor_type {
	None,
	Destroyed,
	Moss,
	Makeshift,
	Steel,
	Golden,
	Diamond,
	Obsidian,
}

var items = {
	None = Item.new(types.General, 0, []),
	Obsidian_leggins = Armor.new(types.Leg_armor, 1, [], armor_type.Obsidian, 300),
	Obsidian_chestplate = Armor.new(types.Torso_armor, 2, [], armor_type.Obsidian, 300),
	Obsidian_armplate = Armor.new(types.Arm_armor, 3, [], armor_type.Obsidian, 300),
	Obsidian_helmet = Armor.new(types.Head_armor, 4, [], armor_type.Obsidian, 300),
	Diamond_leggins = Armor.new(types.Leg_armor, 5, [], armor_type.Diamond, 250),
	Diamond_chestplate = Armor.new(types.Torso_armor, 6, [], armor_type.Diamond, 250),
	Diamond_armplate = Armor.new(types.Arm_armor, 7, [], armor_type.Diamond, 250),
	Diamond_helmet = Armor.new(types.Head_armor, 8, [], armor_type.Diamond, 250),
	Golden_leggins = Armor.new(types.Leg_armor, 9, [], armor_type.Golden, 200),
	Golden_chestplate = Armor.new(types.Torso_armor, 10, [], armor_type.Golden, 200),
	Golden_armplate = Armor.new(types.Arm_armor, 11, [], armor_type.Golden, 200),
	Golden_helmet = Armor.new(types.Head_armor, 12, [], armor_type.Golden, 200),
	Steel_leggins = Armor.new(types.Leg_armor, 13, [], armor_type.Steel, 150),
	Steel_chestplate = Armor.new(types.Torso_armor, 14, [], armor_type.Steel, 150),
	Steel_armplate = Armor.new(types.Arm_armor, 15, [], armor_type.Steel, 150),
	Steel_helmet = Armor.new(types.Head_armor, 16, [], armor_type.Steel, 150),
	Makeshift_leggins = Armor.new(types.Leg_armor, 17, [], armor_type.Makeshift, 50),
	Makeshift_chestplate = Armor.new(types.Torso_armor, 18, [], armor_type.Makeshift, 50),
	Makeshift_armplate = Armor.new(types.Arm_armor, 19, [], armor_type.Makeshift, 50),
	Makeshift_helmet = Armor.new(types.Head_armor, 20, [], armor_type.Makeshift, 50),
	Moss_leggins = Armor.new(types.Leg_armor, 21, [], armor_type.Moss, 100),
	Moss_chestplate = Armor.new(types.Torso_armor, 22, [], armor_type.Moss, 100),
	Moss_armplate = Armor.new(types.Arm_armor, 23, [], armor_type.Moss, 100),
	Moss_helmet = Armor.new(types.Head_armor, 24, [], armor_type.Moss, 100),
	Leather_shoes = Item.new(types.Shoes, 25, []),
	Cutlass = Weapon.new(types.Weapon, 26, [], Weapons.weapons.Cutlass),
	Bow = Weapon.new(types.Weapon, 78, [], Weapons.weapons.Bow),
	Halberd = Weapon.new(types.Weapon, 79, [], Weapons.weapons.Halberd),
	Necklace = Item.new(types.Amulet, 27, []),
	Medkit = Usables.Medkit.new(types.Usable, 28, []),
	Drug = Usables.Drug.new(types.Usable, 45, []),
	Stone = Throwables.Stone.new(types.Usable, 31, []),
	Cyanite = Usables.Cyanite.new(types.Usable, 44, []),
	Reptail = Usables.Reptail.new(types.Usable, 33, []),
	Drug2 = Usables.Drug.new(types.Usable, 34, []),
	Beer = Usables.Beer.new(types.Usable, 35, []),
	Chocolate = Usables.Chocolate.new(types.Usable, 36, []),
	FlaskGreen = Throwables.FlaskGreen.new(types.Usable, 37, []),
	FlaskRed = Throwables.FlaskRed.new(types.Usable, 38, []),
	BananaPeel = Throwables.BananaPeel.new(types.Usable, 47, []),
	CauldronRed = Throwables.CauldronRed.new(types.Usable, 55, []),
	CauldronGreen = Throwables.CauldronGreen.new(types.Usable, 59, []),
	CauldronHand = Throwables.CauldronHand.new(types.Usable, 60, []),
	Molotov = Throwables.Molotov.new(types.Usable, 76, []),
	Carrot = Usables.Carrot.new(types.Usable, 43, []),
}
